# Generated by Django 2.2 on 2022-02-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='cartid',
            new_name='cart_id',
        ),
    ]
