# Generated by Django 2.2 on 2022-02-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220227_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prodt',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='quan',
            new_name='qua',
        ),
    ]
