# Generated by Django 2.2 on 2022-02-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20220227_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prod',
            new_name='prodt',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='qua',
            new_name='quan',
        ),
    ]
